# -*- mode: ruby -*-
# vi: set ft=ruby :

$name = "openlession"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define $name do |i|
    i.vm.hostname = $name
    i.vm.network "private_network", ip: "192.168.33.170"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.name = $name
    vb.cpus = 1
  end

  config.vm.provision "ansible" do |ansible|
    ansible.host_vars = {
      $name => { "ansible_python_interpreter" => "/usr/bin/python3" }
    }

    ansible.playbook = "../ansible/site.yml"
  end
end
